# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: php:8.0-fpm

pipelines:
  default:
    - parallel:
        - step:
            services:
              - mysql
            name: "Build and Test"
            script:
              - bash ./devops/build-server.sh
              - bash ./devops/build-project.sh
              - bash ./devops/run-tests.sh
        - step:
            name: "Deploying to Production"
            deployment: production
            # trigger: 'manual'
            script:
              - bash ./devops/build-server.sh
              - bash ./devops/build-for-production.sh
              - bash ./devops/deploy-production.sh

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: "homestead"
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: "homestead"
        MYSQL_PASSWORD: "secret"
